### ISSUE TITLE
Application not finding things

### ISSUE THREAD

**Issue by rain-1** [tbellembois/gobkm#1]
Hello.

I tried to set this up on alpine linux using the given nginx config.

When I load the page it looks ok (All the css, js and webfont assets are being found) but an alert box popup says 'Not Found'.

In the console it says:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:528 WebSocket connection to 'ws://%7B%7B.gobkmproxyhost%7D%7D/socket/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
(anonymous)	@	main.js:528
/getTags/:1 Failed to load resource: the server responded with a status of 404 (Not Found)
/getTree/:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

Do you know what is wrong?

**Comment by rain-1** [comment]
I had introduced an error when copying the nginx config, sorry!

**Comment by tbellembois** [comment]
No problem. Happy to see that it works.
